### ISSUE TITLE
Do not include fee in the signed "sell amount"

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-swap-ui#135]
"From" deducts fee in estimate but not in signed order

Assume the following order and a fee endpoint returinng a hardcoded 1 wxDAI:

![image](https://user-images.githubusercontent.com/1200333/107074845-95036280-67e9-11eb-88a1-a2e8396093e9.png)

The amount in To (estimated) is computed as if we were selling 1 wxDAI (From - fee). However the order that gets eventually signed and sent to the backend is for selling 2 wxDAI **AND** 1 wxDAI fee on top.

Given the current UX (which is under discussion in ) it should only be signed for a sell amount of 1 wxDAI. Otherwise the smart contract will take up 3 wxDAI from the User's balance and the user is signing a limit price that is way too pessimistic.

Cf this settlement where the fee was 0.1 wxDAI (and I typed in 2 in the From field): https://blockscout.com/poa/xdai/tx/0xd2a58cec3c5ea3a9a6780699a260d42021e49290f3a96e2b260c6874b138e34e/token-transfers

**Comment by anxolin** [comment]
Ok good catch. We thought when we were signing the order that what you sign is the total sell amount (maximum you pay) and separately the fee that is already included. 

I see this parts being confusing, although for now we can put it as the operator/contract expects.
