### ISSUE TITLE
Recent Activity shows wrong price

### ISSUE THREAD

**Issue by fleupold** [gnosis/gp-swap-ui#140]
It's showing my trade executed for 1.89 STAKE received

![image](https://user-images.githubusercontent.com/1200333/107760177-a4266b00-6d29-11eb-9537-8124cfde5b2c.png)

In reality I got 1.90:

https://blockscout.com/poa/xdai/tx/0x97e136466533fd161999188ee8615ea14577307785e41e0bad481f728c01e0a4/token-transfers

**Comment by anxolin** [comment]
I expect this PR will close this one too https://github.com/gnosis/gp-swap-ui/pull/158

**Comment by anxolin** [comment]
I should be should be fixed. @W3stside can u confirm and let @fleupold know, so he can close the issue if it's fixed.

**Comment by fleupold** [comment]
Can no longer reproduce
