### ISSUE TITLE
Intercept estimation tokens

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#15]
Intercept estimation tokens
deduct a tip (hardcoded from a mock function --> get tip)

**Comment by W3stside** [comment]
Linked to #32 

Probably to be split into a couple PRs: 
1. getTip (mock api thing)
2. deduct tip from calculated estimated price (middleware? extend function? hook?)
3. ???

**Comment by anxolin** [comment]
@W3stside what is left to close this one? I believe in the last sync you mentioned there was some doubts regarding the requirements, and u wanted to create a doc with some basic cases to analyse, and with that we would automate some tests.

**Comment by W3stside** [comment]
this is closed by #103
