### ISSUE TITLE
Show the fee

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#161]
We should show the fee to the user

I would suggest to not overcomplicate this change. We could just replace the "liquidity provider fee" by:
- Protocol Fee
- Gas fee

Also, as a specific case. We should account the case where the user inputs to little tokens, so then after fees, he receives 0, and therefore he cannot trade. 

It's good that he cannot trade in that case, but he should be able to understand why. The minimum, is to show the fees, so he get an idea:
- Minimum Received: 0
- Price Impact: XX
- Total fees: 1.000001 WXDAI
  - Protocol Fee:  0.000001 WXDAI
  - Gas Fee: 1 XWXDAI

![image](https://user-images.githubusercontent.com/2352112/108489314-b6f8ec80-72a1-11eb-9dd4-0d4ac71e78f5.png)

@biocom what simple way you think we can show the fees. I thought maybe showing the total as "Protocol and Gas fees": `1.000001 WXDAI` and the rest as a detail in the tooltip

**Comment by biocom** [comment]
I think the simplest way, is as you proposed. I'd try to keep it short + a tooltip:
> Protocol/Gas fees ⍰

or 
> GP & Gas fees ⍰
