### ISSUE TITLE
Trade confirmation modal: Improve the message

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#173]
![image](https://user-images.githubusercontent.com/2352112/108889114-47219380-760c-11eb-9ada-10252ef9ed14.png)

Change this text: `Input is estimated. You will sell at most 0.669872 ETH or the transaction will revert.`

Our tx don't REVERT. They EXPIRE. 

`Input is estimated. You will sell at most 0.669872 ETH or the transaction will expire in XXXX min`

Same for these other tooltips: 

![image](https://user-images.githubusercontent.com/2352112/108889485-ba2b0a00-760c-11eb-8e99-8136d391d3fe.png)
![image](https://user-images.githubusercontent.com/2352112/108889655-ec3c6c00-760c-11eb-8ae4-0119554a748c.png)

We shouldn't use the REVERT word.

**Comment by W3stside** [comment]
updating to be in line with slack comments:

![Uploading Screenshot from 2021-03-08 12-20-45.png…]()

**Comment by anxolin** [comment]
@W3stside I asked about this one why it was in QA, if it was conscious or not, and if it was to add QA context and test instructions. I guess for this one is like the other one you closed, and no QA is needed. I will close it for you, if I'm wrong, just re-open... (and add QA instructions)
