### ISSUE TITLE
Improve sell Ether UX

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#182]
![image](https://user-images.githubusercontent.com/2352112/109146165-bfe73380-7763-11eb-958a-025497152991.png)

The UX for selling ether is not very good. 
Basically, when you trade we send 2 transactions, without any context.
- 1st tx is the WRAP
- 2nd tx is the trade

It's of to go both in parallel, we can be "optimistic" that the approve will succeed, and then, the order will be taken into account after that. But I think we need to be more explicit about the RESTRICTION we have in our exchange, that we cannot sell ETH.

It would be good to think of ideas about this @biocom , @alfetopito 

Some options (just brainstorming):
- We trade directly in Uniswap, we show a message saying that, disencouraging the user to do it?
- When we select ETH, we use instead WETH, but add somehow the WETH balance and ask the user to wrap first
- When we select ETH, we disable trading. We show a button for opening a WRAP modal, and a link/button to change the selection to WETH instead
- We do as we do now, but instead of sending the two tx, we add a new button that shows [WRAP XXX Eth], being XXX the amount the user want to trade. Then, after the tx is sent, we allow to trade.

**Comment by alfetopito** [comment]
> The UX for selling ether is not very good.

I agreed with that from the start :D
My understanding was that, even though we knew there were issues, we would offer to sell ETH anyways.

> When we select ETH, we use instead WETH, but add somehow the WETH balance and ask the user to wrap first

Sort of what uniswap does right now?

**Comment by anxolin** [comment]
> I agreed with that from the start :D
> My understanding was that, even though we knew there were issues, we would offer to sell ETH anyways.

Yep, now we have the option. the point is, iterate now. Yes, it's basically what we discussed already. Just making the issue so we think.

> Sort of what uniswap does right now?
No uniswap allows to sell ETH directly. This is more, like making the user aware he has to wrap.

**Comment by anxolin** [comment]
Also, it was mentioned in the last test, we have an issue with selling ETH if WETH is not approved.

Now require 3 tx: Approve, Wrap, Trade (meta)
