### ISSUE TITLE
Issues with hex numbers

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#199]
https://gnosisinc.slack.com/archives/CSGLUC1BN/p1614870190011300

Aparenty metamask allows also to display big numbers numbers in their decimal format, which is more readable.

**Comment by alfetopito** [comment]
I think this was auto-fixed. Amounts are being displayed as decimals now:

![screenshot_2021-03-11_10-59-25.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/84555121-3319-4f6d-8101-ea79d034fc3f)
