### ISSUE TITLE
"Insufficient Balance" when selecting "Wrap ETH" 

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-swap-ui#208]
Swap page now disables ETH and has an option to wrap ETH from the descriptor modal - however selecting doesn't clear the "Insuffiencient Balance" error

Fix this

From Anxolin comment:

Awesome! Great work with this one. 
I love the functionality and messages.

I think one problem though, is this message (as you see, I have balance):
<img width="1202" alt="Screenshot at Mar 05 12-33-13" src="https://user-images.githubusercontent.com/2352112/110110676-7aec7e00-7daf-11eb-9b1f-0f500c4f8e5b.png">

**Comment by alfetopito** [comment]
To be honest, this is the same behaviour as Uniswap
![screenshot_2021-03-10_13-43-11.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/e5b5dc86-4eb6-4fef-bfc9-b861ffbd6b07)
