### ISSUE TITLE
[Fee] When input amount is lower than fee amount - show relevant message

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-swap-ui#211]
**GP/Gas fees is only visible when trade is validated**

Scenario: user selects input amount that is lower than the minimalFee threshold, the trade will not be validated. However user cannot see the fee amount at this point so it is unclear with the `Insufficient Liquidity` what is going on

Solution: always show `sellToken` fee amount and a better message for clarity

**Comment by W3stside** [comment]
imo this one should wait on #251

**Comment by W3stside** [comment]
reason being the return shape from the new endpoint facilitates the required code changes significantly

**Comment by MareenG** [comment]
I tested it and it works nicely. It is a great improvement. 
The style is a bit different than the other notification:
<img width="375" alt="Bildschirmfoto 2021-03-24 um 09 52 53" src="https://user-images.githubusercontent.com/34510341/112281821-c72c2f00-8c86-11eb-9881-a233de2a945f.png">
<img width="380" alt="Bildschirmfoto 2021-03-24 um 09 52 37" src="https://user-images.githubusercontent.com/34510341/112281787-bd0a3080-8c86-11eb-99ac-32172df07218.png">


I guess not many trades will be placed at values near the GP Fee. However I was wondering if it would make sense to show a warning if someone wants to place such an order. Let's say the  Fee is 0.838**2** DAI and I would place an order around 0.838**3** DAI it could show that a majority of my order will be used to cover the fee.
