### ISSUE TITLE
Order not found in Explorer

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#213]
When the SWAP UI sees a swap event in the contract for the order, it shows a notification to the user right away

If the user follows the link and goes to the explorer, in some cases he will find a "Not found order" message
This is because the UI and the Backend might have a different view of the state:
- The UI sees a mined block with 
- The Backend, haven't seen that block yet, or is in another chain that hasn't  the transaction yet

Some options:
- Wait for confirmations in FE
- Use the backend for being notified about a traded transaction: so they share the same view

RELATED: I assume, the possible solution of this issue, will also solve https://github.com/gnosis/gp-swap-ui/issues/165

cc @fleupold @W3stside

**Comment by fleupold** [comment]
I think querying the backend for this information (polling based) should already be possible and fast.
