### ISSUE TITLE
Issue with expire date

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#214]
Somehow @fleupold managed to create an order with 85 years as the expiration date

Two questions come to mind:
- 1. where did this error ocur, backend/frontend?
- 2. Why 85 years?

**1) It is probably a frontend issue**
The backend cannot modify the expiration date. Although, this is assuming the backend stored correctly the expiration date in their DB. So a quick review in the smart contract would answer if this order expiration date was so big. 

If the smart contract tell us is a big expiration date, it's 100% the frontend. Since the backend cannot modify the signed data. 

**2) Felix mentioned is because is the maximum amount they allow**
However, we might want to review this part, because the backend shouldn't modify what is in the smart contract. 

Unless, this is the true maximum in the smart contract, then is all fine!

EDIT: It's all fine with question number 2, since the datatype is `uint32`, which yields this max value:
![image](https://user-images.githubusercontent.com/2352112/110144780-00d0ef00-7dd9-11eb-9682-555be93d0dc0.png)

**Comment by alfetopito** [comment]
Can you add the order id to this issue? Would help a bunch to debug :)

**Comment by anxolin** [comment]
Yep, sorry, it was https://protocol-explorer.dev.gnosisdev.com/orders/0xf475c72260020709bbf61c3c58484015adbe298fc7d9250f12164a83540bcc78e0b3700e0aadcb18ed8d4bff648bc99896a18ad1ffffffff

**Comment by alfetopito** [comment]
Looks correct from the explorer point of view.
And now I realize the repo where this was opened on, so it wasn't related to the explorer at all from the start :)

**Comment by anxolin** [comment]
> In the smart contract validTo is a u32, max u32 is 4294967295 which in epoch is in roughly 85 years.

yep, I edit it after double checking that. Anyways, for now we haven't been able to reproduce. We might have to ask you for help making it again :) 
We have it in our backlog the task of testing this more, but feel free to break it again if u have a hint on what u did last time

**Comment by alfetopito** [comment]
Manged to sort of reproduce

https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xd6a42b98814f1183b3b01d277870066f379867a15247cf9ec2f7c434573566055b0abe214ab7875562adee331deff0fe1912fe42ffffedd4

![screenshot_2021-03-10_14-51-15.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/e45da14d-7083-4282-aa4a-925b7e5a3f4d)

I got there by manually calculating the difference, in minutes, from now (1615416601) until the end of times (max uin32 == 4294967295), minus a few minutes:
`(4294967295 - 1615416601)/60 ~= 44659178 ~= 44659000`

Set that value into transaction deadline
![screenshot_2021-03-10_14-55-49.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/9a97d2af-79f7-4d53-be1d-0e997e803fc4)

---

Another easier way would be to set that value to `0`.
In that case, the deadline is [`undefined`](https://github1s.com/Uniswap/uniswap-interface/blob/HEAD/src/hooks/useTransactionDeadline.ts), and we default to [`max uint32`](https://github.com/gnosis/gp-swap-ui/blob/9bf75c5338d679da56a52012436f0ba24ceca89f/src/custom/hooks/useSwapCallback.ts#L35)
But the UI doesn't allow the value to be set to `0` AFAICT.

---

Another way is going to local storage and manually setting `userDeadline` value to `0`, bypassing the UI validation
![screenshot_2021-03-10_15-01-54.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/24d55b4e-b169-49bd-aa4d-1732c5734642)

---

But assume Felix done none of that.
My best guess would be that for some reason, the current [block timestamp fetch returned `undefined`](https://github1s.com/Uniswap/uniswap-interface/blob/HEAD/src/hooks/useCurrentBlockTimestamp.ts), causing the order to be set to default of max uin32.

---

A solution in this case could be to do like Uniswap does, and don't proceed with the order unless a user deadline is set, not defaulting to max uin32.

@anxolin @W3stside thoughts on this?

**Comment by fleupold** [comment]
I swear under oath that I didn't enter the advanced settings at any time (I didn't set a manual deadline).
