### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#226]
In the account overview page the order links in the recent activities are not working. 
The Tx links are working
<img width="514" alt="Bildschirmfoto 2021-03-11 um 10 14 00" src="https://user-images.githubusercontent.com/34510341/110764231-14ee7380-8253-11eb-88d5-6a8dac234ac3.png">

**Comment by alfetopito** [comment]
Do you against which version was that?
I just tried and they all worked. I suspect one of my PRs merged today fixed this.

**Comment by MareenG** [comment]
It didn't work in staging https://gp-swap.staging.gnosisdev.com/#/swap
I just tried the dev environment and the link work

**Comment by W3stside** [comment]
i think we can safely close this as dev works, thanks @MareenG
