### ISSUE TITLE
UI crash while setting transaction deadline

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#236]
I was looking for boundary setting for the transaction deadline and entered a quite high value (10^15).
The UI crashed and all I got was a white browser screen. I only could restore by clearing all site data.
I doubt anyone will ever enter such a high value but it might be worth to limit the input to a reasonable value.

**Comment by alfetopito** [comment]
Should be fixed by https://github.com/gnosis/gp-swap-ui/pull/232
Just tested it locally and it works.

Unfortunately, the PR does not have the deploy link for some reason. Will look into that.

**Comment by anxolin** [comment]
@MareenG , this one should be solved and included in the version. Although, it would be good if u don some more tests and close if it doesn't reproduce anymore

**Comment by MareenG** [comment]
It is solve and the error doesn't appear anymore
