### ISSUE TITLE
Privacy and cookie policy

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#241]
Less prio than the swap UI privacy and cookie policies

Sister issue of https://github.com/gnosis/gp-ui/issues/303

Review:
* [x] Privacy policy: https://docs.google.com/document/d/17Abd5RzzibF0o4te7lDynRS_XynrwCkUj7IaO3FA60g/edit#
* [x] Cookie policy: https://docs.google.com/document/d/1CTFhp2jUrCwfRnNJpWugFuVii9Foy3MaZYhkoBojMDY/edit?usp=sharing

Also:
* [x] Convert to Markdown:
* [x] Create pages
* [x] Adapt footer

Similar to what the Safe has:
![image](https://user-images.githubusercontent.com/2352112/111311409-7dc45a00-865e-11eb-9f8c-6bd5f630ef8d.png)

And the footer, see it in action in https://gnosis-safe.io:
![image](https://user-images.githubusercontent.com/2352112/111311789-e9a6c280-865e-11eb-8515-f5662d7bee82.png)

**Comment by W3stside** [comment]
[x] Reviewed Privacy Policy
[ ] Reviewed Cookie policy
