### ISSUE TITLE
Disclaimer - Terms and Conditions Policy

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#250]
First iteration of the text:
https://docs.google.com/document/d/1rt5G48wgJAHaUb3P7f2CzFdQHshMkdWbu8UsCx6-Y38/edit

Related to https://github.com/gnosis/gp-swap-ui/issues/241, sister of https://github.com/gnosis/gp-ui/issues/311

And the footer, see it in action in https://gnosis-safe.io:
![image](https://user-images.githubusercontent.com/2352112/111311789-e9a6c280-865e-11eb-8515-f5662d7bee82.png)

Also:
* [x] Convert to Markdown:
* [x] Create page
* [x] Adapt footer
* [ ] Include it in the Clickwrap

**Comment by MareenG** [comment]
I can't find a link to test it. Should this be tested within in the 0.9 release?
