### ISSUE TITLE
Update fee endpoint

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#251]
Use the new fee endpoint model
https://github.com/gnosis/gp-v2-services/pull/350

**Comment by anxolin** [comment]
@W3stside this issue is in QA, but is not clear what to test and how to test it. Preconditions/Test/Expectations

Could you let @MareenG know?
After that, you can remove the on-hold tag

**Comment by W3stside** [comment]
@anxolin I added the test specs in the release pr v0.9. I discussed with
Mareen and we agreed it's easiest to consolidate QA instruc. in release PRs
unless a pr is important and not immediately connected to a release

**Comment by anxolin** [comment]
Ok, so I understand we should close this one
