### ISSUE TITLE
Add Alpha mark

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#282]
![image](https://user-images.githubusercontent.com/2352112/111627633-8ac48300-87ef-11eb-8c88-79915aa15596.png)

We've been instructed, we should leave very clear that this is an alpha version, so people trade on their own risk

**Comment by biocom** [comment]
@anxolin Shows up also in the GP theme. Undesired?
<img width="763" alt="Screen Shot 2021-03-22 at 15 57 07" src="https://user-images.githubusercontent.com/31534717/112011284-6850a380-8b28-11eb-849b-bf16576c2fa3.png">

Same for the FEEDBACK button.

**Comment by anxolin** [comment]
Yes, good point. But I think I'll delay removing it until we need to launch a second project using the same codebase, cause I'm not sure if this will be an issue, and its pretty easy to fix if it is.
