### ISSUE TITLE
Remove/hide dark mode

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#284]
![image](https://user-images.githubusercontent.com/2352112/111657725-003e4c80-880c-11eb-9f79-d2a083cd6785.png)

**Comment by alfetopito** [comment]
:bulb:  oh oh oh, for the dark cow mode, the sun is replaced by a moon, the cows are sleeping (no sunglasses, maybe sleeping hats instead, pijammas (lol, with a cow spot pattern), the owl is active and more prominent

so many ideas :exploding_head:

**Comment by anxolin** [comment]
Ahaa, bring all those ideas to #286
