### ISSUE TITLE
Miscellaneous about cow swap version

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#288]
* [x] 1. Should we review the color of this text. At least for the cow, to add more contrast, but I think also for GP, since the color was a bit weird imo:
![image](https://user-images.githubusercontent.com/2352112/111660722-a68b5180-880e-11eb-86c6-7ccf1409469f.png)

* [x] 2. Are these buttons may to big? @biocom what do you think
![image](https://user-images.githubusercontent.com/2352112/111661008-eeaa7400-880e-11eb-97d2-f637e0a38501.png)

* [x] 3. Are we sure we want to use that blue for the widget. Imo, white is nicer

![image](https://user-images.githubusercontent.com/2352112/111661282-303b1f00-880f-11eb-83c2-921084a1c7f7.png)

![image](https://user-images.githubusercontent.com/2352112/111661221-21546c80-880f-11eb-858f-fdc0c834f2e6.png)

* [ ] 4. We lost the "toggle", at some point in the past we had highlighted the selected tab here:
![image](https://user-images.githubusercontent.com/2352112/111661536-624c8100-880f-11eb-946a-5c2d2709bec6.png)

* [x] 5. Should we add more contrast or do the background of the network less transparent, so it's more visible?
![image](https://user-images.githubusercontent.com/2352112/111661695-88722100-880f-11eb-9e4c-5f87dd58cd35.png)

* [x] 6. Remove: #289
![image](https://user-images.githubusercontent.com/2352112/111661775-9f187800-880f-11eb-9f8c-764b9889b5cb.png)

* [x] 7. Title is wrong #292 
![image](https://user-images.githubusercontent.com/2352112/111661908-beafa080-880f-11eb-8af7-7cb10a172ee2.png)

* [x] 8. We don't have favicons with the cow. #292 

* [ ] 9. We need thicker borders in the pop us, right? to make them also look cartoonish
![image](https://user-images.githubusercontent.com/2352112/111662384-282faf00-8810-11eb-829c-cb75bd85eff4.png)

same for modals: 
![image](https://user-images.githubusercontent.com/2352112/111677744-cc6d2200-881f-11eb-9150-a17c316c196c.png)

* [ ] 10. Text contrast 

![image](https://user-images.githubusercontent.com/2352112/111662566-52816c80-8810-11eb-8d5c-54a28331490c.png)

* [x] 11. Add an alpha mark
https://github.com/gnosis/gp-swap-ui/issues/282

* [x] 12. Broken images
https://github.com/gnosis/gp-swap-ui/issues/264

**Comment by W3stside** [comment]
@anxolin @biocom agree on all these points, let's pls implement

**Comment by anxolin** [comment]
I did some of them as PRs, already check them and added the link. I left the ones related to CSS

**Comment by biocom** [comment]
Just some points to address (will handle these in separate PR's)
1) Yes, need to update the contrast colors there.
2) They are, but wasn't so straightforward at the time to apply a different style for it (given it shares the same button component as the SWAP one..). Will handle this.
3) I have to disagree on using white: The contrast is way more hard on the eyes. The blue matches the swapping container and makes it consistent. However some general touch ups are recommended in this token selector otherwise.
4) Yes, that's for both themes. Again because of inheritance/complexity I left 'the best for last' to fix... :)
5) We could yeah. Will look into it.
9) Yes, will look into that one.
10) Agreed. Again a harder one to tackle as compared to the others. Will handle this.

**Comment by annamsgeorge** [comment]
I have to disagree on using white: The contrast is way more hard on the eyes. The blue matches the swapping container and makes it consistent. However some general touch ups are recommended in this token selector otherwise. 
--> I am with Michel on this! I think the blue works better.

**Comment by anxolin** [comment]
Yep, this misc are quick thought I had while having a review on the theme. Let's break this into smaller things, and address the ones we think are easy and good to have. 

Take this misc as just suggestion, Im ok leaving the background blue. I normally like white background, and for contrast to use lighter text color, however this topics are better handled by Michel, im a color 🐒

**Comment by anxolin** [comment]
Cross-linking here one small one that maybe we want to look at as part of this last review https://github.com/gnosis/gp-swap-ui/issues/314

**Comment by biocom** [comment]
Closing this one and created separate issues for the pending items:

- https://github.com/gnosis/gp-swap-ui/issues/363
- https://github.com/gnosis/gp-swap-ui/issues/362
- https://github.com/gnosis/gp-swap-ui/issues/361
