### ISSUE TITLE
Incorrect trade success message

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#307]
@koeppelmann  reported:

> Could do a sucessfull trade - everything worked just fine - but the notification for the trade showed I traded 0 tokens for 0
In the list of recent tx it is shown correctly (107 for 79)

![image](https://user-images.githubusercontent.com/2352112/111970237-5dcbe500-8afb-11eb-815d-03fbdc23efc0.png)

![image](https://user-images.githubusercontent.com/2352112/111970265-658b8980-8afb-11eb-9199-7d2bf707795b.png)

**Comment by anxolin** [comment]
This is a duplicate with #258

**Comment by MareenG** [comment]
I wasn't fast enough to get a screen shot. Today I got the message that I traded 0.2 ETH for 846.7 ETH instead of 0.2 Uni for  846.7 DAI

**Comment by anxolin** [comment]
> I wasn't fast enough to get a screen shot. Today I got the message that I traded 0.2 ETH for 846.7 ETH instead of 0.2 Uni for 846.7 DAI

Do you remember if it was a buy/sell order?

**Comment by anxolin** [comment]
Closing because this is being tracked in #258

**Comment by MareenG** [comment]
Should have been a sell order
