### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#310]
If I minimize the screen the wallet information which is usually on top moves to the bottom. 
It is a bit unintuive that it is suddenly in the bottom, additionally does it cover the links in the footer. 
<img width="988" alt="Bildschirmfoto 2021-03-22 um 14 41 29" src="https://user-images.githubusercontent.com/34510341/111999533-5fa6a000-8b1d-11eb-8d9d-86bfc5959837.png">
<img width="936" alt="Bildschirmfoto 2021-03-22 um 14 41 19" src="https://user-images.githubusercontent.com/34510341/111999537-60d7cd00-8b1d-11eb-8b2a-aa4f2913f7fe.png">

**Comment by anxolin** [comment]
I believe this is intended. Is a bad UX practice @michelbio ?

**Comment by MareenG** [comment]
If we have policies linked in the footer it might be an issue.

**Comment by anxolin** [comment]
Well, we can have them in the same place, or have a "policies" link for responsive

**Comment by biocom** [comment]
It's intended and inherited from UNI. Think it's fine personally. The footer element is fixed. The rest of the page is scrollable. Meaning anything in the footer (e.g. policy links) would become visible.

**Comment by anxolin** [comment]
mareen, Michel made the point that the policies can still be accessible in the three-dotted menu in the top right corner (we removed this menu, but we can easily bring it back). So i think, all good :)

**Comment by MareenG** [comment]
We, however, cover the contract details, web and block links. They can't be access via the menu.

**Comment by biocom** [comment]
@MareenG Two options I see there:
- Add those contract/web/block links to the main menu (for mobile).
- Display them as usual on mobile and allow for scrolling the page (my recommendation).

As for the wallet being below the page, my thoughts: Given the available width on mobile this is good practice because:
- On mobile the top section has limited available width (Logo + Main menu)
- Hence using the footer is a good way to accommodate users on mobile.

**Comment by MareenG** [comment]
I also don't mind anymore that the info is now below the page. Once getting used to this it is better than squeezing it into the header :)

> Display them as usual on mobile and allow for scrolling the page (my recommendation).
I personally would also go for this option. 
The issue is also present when minimizing the screen on for the web application not only on mobile

**Comment by biocom** [comment]
> The issue is also present when minimizing the screen on for the web application not only on mobile 

Got a screenshot? On desktop, if you'd minimize it down to dimensions of a mobile viewport, that would give the same effect (mobile vs. mobile responsive).

**Comment by MareenG** [comment]
https://user-images.githubusercontent.com/34510341/116205263-d7c83d00-a73d-11eb-8254-fb44a55ceb83.mov

**Comment by biocom** [comment]
Thanks for sharing. I'll try to address this in a PR.

**Comment by biocom** [comment]
Closing as this has been addressed by PR #539 (merged)
