### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#311]
There is no link directing to WEB it only directs you to [CONTRACTS](https://rinkeby.etherscan.io/address/0x4E608b7Da83f8E9213F554BDAA77C72e125529d0)
<img width="190" alt="Bildschirmfoto 2021-03-22 um 15 56 07" src="https://user-images.githubusercontent.com/34510341/112010018-35f27680-8b27-11eb-9c89-dd20c0db773f.png">

**Comment by anxolin** [comment]
![image](https://user-images.githubusercontent.com/2352112/112869975-0363f300-90be-11eb-83e1-9783b60c11fd.png)

We might want to use the same info as the Explorer
