### ISSUE TITLE
Usdc decimals are wrong in Rinkeby

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#328]
Review this, since it was reported. 
The contract and the token list information should match.

**Comment by MareenG** [comment]
Same for USDT see #280

**Comment by anxolin** [comment]
USDC in rinkeby has 6 decimals in the contract https://rinkeby.etherscan.io/token/0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b
also in our token list:
![image](https://user-images.githubusercontent.com/2352112/112609212-916c7f00-8e1b-11eb-9b3d-fb658e2fe633.png)


USDT has 6 decimals in the contract: https://rinkeby.etherscan.io/token/0xa9881E6459CA05d7D7C95374463928369cD7a90C 
Also in the list:
![image](https://user-images.githubusercontent.com/2352112/112609359-be209680-8e1b-11eb-9ba4-c111ac4e5a15.png)

However, in compound list there's a USDT with 18 decimals:
https://rinkeby.etherscan.io/token/0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02

As you see uniswap is also not correct. This is becase of the price. Whomever who added liquidity, did it at the wrong price:
![image](https://user-images.githubusercontent.com/2352112/112609687-1d7ea680-8e1c-11eb-9429-b464e4c104c9.png)

**Comment by anxolin** [comment]
Closing, because I don't think there's an issue with this one
