### ISSUE TITLE
Update contracts to alpha 15

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#338]
* PR services: https://github.com/gnosis/gp-swap-ui/pull/253
* Contract changes: https://github.com/gnosis/gp-v2-contracts/issues/338

Comment from @vkgnosis 
We now have a working branch for the contracts upgrade in services. There are some changes to the http api related to that https://github.com/gnosis/gp-v2-services/pull/413/files#diff-2fdf392407567af4a81fd7ed6063925fc058abfeefdf5fb1db0c7daaef1c351a :
* appdata used to be a 32bit integer, is now 32 bytes, hex encoded
* new optional (nullable) field receiver which is the receiver address (like in https://github.com/gnosis/gp-v2-contracts/blob/120600868f7c14f5d4159fad07f4de2977cd17a0/src/ts/order.ts#L8)
* new field signingScheme which corresponds to https://github.com/gnosis/gp-v2-contracts/blob/120600868f7c14f5d4159fad07f4de2977cd17a0/src/ts/sign.ts#L36 . So far we only support eip712.

https://gnosisinc.slack.com/archives/CSGLUC1BN/p1616666411012300

**Comment by fleupold** [comment]
To run locally, check out the `contract-upgrade` branch and run

```
cargo run --bin orderbook -- --node-url https://rpc.xdaichain.com/
```

This should give you a local version of the xDAI API with which you can test order placement.

**Comment by vkgnosis** [comment]
> So far we only support eip712.

`ethsign` is supported too now
