### ISSUE TITLE
Missing surplus on BUY orders

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-swap-ui#346]
I feel like this order should have some surplus, given the difference between limit and execution prices, but it doesn't.

https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0xfb2b969bf74fc47bc1b03c6a934f138d42637e663c458c601addb480c5c1c5a55b0abe214ab7875562adee331deff0fe1912fe42605d00aa

![screenshot_2021-03-25_14-29-58.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/cc4ba644-c450-4ddf-8bde-c5776e7a3cb5)

Investigate further whether there's anything wrong or not.

**Comment by alfetopito** [comment]
Guess the issue is how we calculate surplus for buy orders.
Another one with the same problem https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x8bd5855c020959cf31fd90271de0c35dfca80382704cb43124743330622aa7635b0abe214ab7875562adee331deff0fe1912fe42605d0251

**Comment by anxolin** [comment]
Closed, duplicated of #330
