### ISSUE TITLE
Wrong tooltip for minimum received

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#350]
![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/fab21dcc-e425-430d-9576-d7a3fc7984dc)

This tooltip doesn't refer to the minimum received.

**Comment by anxolin** [comment]
I would suggest something like:

`Minimum tokens you received. This accounts for the current price and your slippage (0.5%). If the price moves beyond your slippage, you won't trade but also you won't pay any fees or gas.`

The 0.5% is an example. I suggest showing the actual slippage.

@annamsgeorge

**Comment by annamsgeorge** [comment]
We should def adjust that, good catch. I suggest slight changes to your proposal Anxo: 

Minimum tokens you'll receive. This accounts for the current price and your chosen slippage (0.5%). If the price moves beyond your slippage, you won't trade but also you won't pay any fees or gas.
