### ISSUE TITLE
Allow to buy ETH

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#355]
After upgrading the contracts we can buy but not sell ETH.

**Comment by alfetopito** [comment]
Swap and explorer now support it.
Pending backend services.

**Comment by anxolin** [comment]
@alfetopito should we wait for having all ready so Mareen can do the end to end test?

**Comment by alfetopito** [comment]
Sure thing.
I moved to QA because after closing I realized I had skipped that step in the flow.
Will close again
