### ISSUE TITLE
Expert mode it partially  functioning

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#359]
# Description
If I enable the expert mode the confirm modals are still enabled

# How to Reproduce

- Enable expert mode
- Place a swap with an price impact higher than 15%
- confirm swap

# Behaviour
Confirm modal pops up

# Expected Behaviour
no modal pop up

# Screenshots/Videos
<img width="465" alt="Bildschirmfoto 2021-03-30 um 12 35 01" src="https://user-images.githubusercontent.com/34510341/112975855-7029cc80-9154-11eb-9244-6f76ae3bc995.png">

# Note
unimportant sidenote the wizard could be replaced by cow related icon e.g. Supercow
<img width="223" alt="Bildschirmfoto 2021-03-30 um 12 37 13" src="https://user-images.githubusercontent.com/34510341/112976086-b5e69500-9154-11eb-9392-44c8c10a2187.png">

**Comment by MareenG** [comment]
For Uniswap it is the same. 
I was just assuming that the confirmation modals should be disabled as it states in the info text `Bypasses confirmation modals and...` If they should remain it might be good to rephrase or is sth else meant with the confirmation modal?

**Comment by anxolin** [comment]
> unimportant sidenote the wizard could be replaced by cow related icon e.g. Supercow

Great idea 
![image](https://user-images.githubusercontent.com/2352112/114708588-d48b8500-9d2b-11eb-93d1-f58a1b8dd949.png)

Leandro made already a similar issue. By the way, you can always open issues with these ideas. We are labeling with the "fun 🐮" tag:

![image](https://user-images.githubusercontent.com/2352112/114708736-0ac90480-9d2c-11eb-9963-71415df39241.png)
