### ISSUE TITLE
The app id should be 1, but currently shows 0

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#371]
**Describe the bug**
The app id should be 1, but currently shows 0

**How to Reproduce**
* Sign an order
* Observe the appData value

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/113143029-f06f3100-922b-11eb-9504-75c6890d269d.png)

**Additional context**
Probably is just setting the env var in Github

**Comment by nlordell** [comment]
Why not `0xbeef`?
