### ISSUE TITLE
Test release v0.8

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#376]
We currently have a draft of v0.8.0 release. It still don't work because uses the newest contracts. @alfetopito and @fleupold will be coordinating the upgrade tomorrow. 

After we do the upgrade, we can do some basic smoke tests, to verify the happy paths.
https://github.com/gnosis/gp-swap-ui/pull/375

We are aware the release is under documented. We will try to provide better context tomorrow.

**Comment by W3stside** [comment]
@MareenG Leaving some more information on testing below:


    

### 1. consider fee
### 2. tooltip info on sell/buy inputs
  - #### tooltip should show:
      - Sell swap: fee tooltip shown in "To" input field, and numerically represented in receive token: ![Screenshot from 2021-04-05 14-23-22](https://user-images.githubusercontent.com/21335563/113578337-8c2ce280-961a-11eb-8fe4-c18ef60d7cc7.png)
      - Buy swap: fee tooltip shown in "From" input field, represented numerically in sell token:
![Screenshot from 2021-04-05 14-25-11](https://user-images.githubusercontent.com/21335563/113578453-c0a09e80-961a-11eb-8f5c-a3039f9c66d5.png)
### 3. swap dropdown (when buy/sell and amounts selected): ![Screenshot from 2021-04-05 14-25-42](https://user-images.githubusercontent.com/21335563/113578548-dd3cd680-961a-11eb-8f62-ce1221c80e0f.png)
### 4. modals after selecting "Swap": ![Screenshot from 2021-04-05 14-33-06](https://user-images.githubusercontent.com/21335563/113579247-ec705400-961b-11eb-8462-5092e47ba081.png)

### 5. Metamask/wallet confirmation modal w/order data
  - #### infomation is correctly represented in atoms (token decimals multiplied by amounts) - e.g `OWL` @ `18` `decimals`, buying `20`, shown as  `20000000000000000000`

  - #### When order `type` = `buy` - make sure:
![Screenshot from 2021-04-05 15-09-52](https://user-images.githubusercontent.com/21335563/113583759-f85f1480-9621-11eb-9e95-d5a789580ef4.png)
    - `sellAmount`: shown as slippage adjusted amount MINUS the `feeAmount` in atoms (see step 6 for slippage calculation). `sellAmount` + `feeAmount` divided by it's decimals `(amountInAtoms / 10**decimals)` should equal the exact amount input by you in the "From" input field 
    - `buyAmount`: should be the exact amount you typed in, but represented in atoms

 - #### When order `type` = `sell` - make sure: 
![Screenshot from 2021-04-05 15-11-36](https://user-images.githubusercontent.com/21335563/113584214-89ce8680-9622-11eb-946a-4f9d4c80d9f7.png)
  - `sellAmount`: should be the exact amount you typed in, but represented in atoms
  - `buyAmount`: should be the `buyAmount` adjusted for slippage. The amount shown in the `Minimum received` section in the dropdown calculated by: `buyAmount` shown in "To" field `* (1 + slippage)`:
![Screenshot from 2021-04-05 19-07-36](https://user-images.githubusercontent.com/21335563/113608265-3b30e480-9642-11eb-8272-e9b4b3166138.png)
 
### 6. toast notifications after submitting a swap:
  - #### submission message should use SLIPPAGE amounts (original sell/buy amount * (1 + slippage)) 
    - [sell swap] e.g: selling exactly X WETH = 10[expected OWL buy]   * (1 - 0.005[0.5% slippage]) = Swap X WETH for at least 9.95 OWL 
![Screenshot from 2021-04-05 15-11-43](https://user-images.githubusercontent.com/21335563/113583218-458eb680-9621-11eb-8a7a-251845e8cf85.png)

    - [buy swap]  e.g: buying exactly X OWL   = 10[expected WETH sell] * (1 + 0.005[0.5% slippage]) = Swap at most 10.05 WETH for X OWL: 
![Screenshot from 2021-04-05 15-10-00](https://user-images.githubusercontent.com/21335563/113583081-17a97200-9621-11eb-9a2b-6fdc9f5b2346.png)

  - #### swap confirmation message should use actual traded amounts which can be verified on Explorer

**Comment by W3stside** [comment]
Edited comment as @MareenG correctly pointed out I was wrong about what to see in sellAmount when selling

**Comment by W3stside** [comment]
@MareenG the calculations for buy/sell with slippage and fee are not in this version, thanks for pointing that out. We will make a release for this on Monday - `v0.9` likely. For now please skip instructions for correct numbers in step `5`
Thanks!
