### ISSUE TITLE
Horizontal line in header

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#388]
**Describe the bug**
horizontal line in the header which wasnt there before and looks odd

**Screenshots**
<img width="722" alt="Bildschirmfoto 2021-04-07 um 10 33 09" src="https://user-images.githubusercontent.com/34510341/113836114-e3eb5b00-978c-11eb-8f31-ad0eef6e9a5b.png">

**Comment by alfetopito** [comment]
@biocom I believe you are removing this with the old-new `alpha` label on top, right?

**Comment by biocom** [comment]
Yes, will be part of PR https://github.com/gnosis/gp-swap-ui/pull/385
