### ISSUE TITLE
Approve tokens after new release

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#393]
Everytime we have a new release users have to approve tokens eventhough they did this before in the older version. 
Depending on how often this happens this might annoy users especially as they have to pay for it.
Not sure if this is possible or how difficult this is but maybe there is a way to avoid it.

**Comment by alfetopito** [comment]
This is because there was a new version of the contracts.
We do not expect this to happen often, or at all, once we are live.
During develop though, this is expected.

**Comment by anxolin** [comment]
Yep, but good call raising it, it's good we confirm is because of a contract upgrade.
