### ISSUE TITLE
Consider using account address as default `receiver` instead of `0x0..0`

### ISSUE THREAD

**Issue by nlordell** [gnosis/gp-swap-ui#394]
This issue was moved from https://github.com/gnosis/gp-v2-services/issues/452

The GPv2 contracts have special semantics for the `0` address when used as the order's `receiver` field. This special value is reserved for encoding "the receiver is the same as the signer". This decision was done because:
- `0`s are more efficient in calldata (they cost 4 gas per byte instead of 16)
- It is the most common value for the receiver

The issue with this is that users signing an order may see `receiver: 0x0..0` and get confused and think that the order will send the proceeds to `0x0..0` instead of their own account.

This issue proposes instead setting the receiver to be the signing account by default in order to avoid confusion about the signed data. This would make the order to behave the same as it does today but:
- Have slightly different signed data and signature
- Cost `(16 - 4) * 20 = 240` additional gas per order

/cc @anxolin @bh2smith

**Comment by alfetopito** [comment]
I see no problem changing that on our side and I agree it gives better visibility for users.

Is this ok regarding the additional gas from backend/contract/solver point of view?

**Comment by bh2smith** [comment]
I would have been a lot happier if we could have just stored null in the database instead of the zero address. If this change is gonna go through then we should probably also make the receiver field required on the services side.

**Comment by nlordell** [comment]
> if we could have just stored null in the database instead of the zero address

The issue is that there is no concept of "nullable" types for EIP-712 typed data signature. So regardless of how you store it in the database, the user will still have to sign with address `0x0...0` and doesn't really help in terms of removing ambiguity. Besides, users don't inspect the database rows (I hope :laughing:), so I doubt they really care about how its stored.

> Is this ok regarding the additional gas from backend/contract/solver point of view?

Its about 0.3% of the total gas cost of an order, so fairly minimal. This is the major downside to implementing this, and the tradeoff for removing ambiguity in the signed data.
