### ISSUE TITLE
Cow cursor missing

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-swap-ui#401]
Cow cursor is not displayed when the swap has a high slippage and `Swap anyway` button is displayed
![screenshot_2021-04-09_13-58-03.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/6cb230de-c62b-4a10-9787-63a93cc79299)

**Comment by anxolin** [comment]
This is addressed by one of your recent PRs, right @michelbio. If so and solved, we can close

**Comment by biocom** [comment]
Addressed by PR https://github.com/gnosis/gp-swap-ui/pull/580
