### ISSUE TITLE
ETH/WETH message on xDai

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-swap-ui#404]
![screenshot_2021-04-09_14-07-20.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/1f278818-ea2e-4146-bdd7-5edba929612d)

**Comment by anxolin** [comment]
@alfetopito can u add a bit more of context. This error refers to a message or that you cannot actually trade in Nifty Wallet?

**Comment by alfetopito** [comment]
Ah no, ignore the error message.
The point is:
  I'm on xDai network and it says: `ETH cannot be traded. Use WETH.`
  I would expect instead: `xDai cannot be traded. Use wxDai.`

**Comment by anxolin** [comment]
Ok, thx!

**Comment by anxolin** [comment]
Closing because we will address it https://github.com/gnosis/gp-swap-ui/issues/443
