### ISSUE TITLE
Make sure we setup new domain for production

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#406]
maybe cow-swap.com

The name of the app is Cow Swap, we considered changing it to Cow Trade, but trade has some bad connotations and some people are against this. So we are changing the domain instead of the name

**Comment by biocom** [comment]
Agreed. I mentioned this in a previous discussion, that I think it's important to align the front-end name (CowSwap) with the domain used. Not only from a recognition point of view, but to ensure security/prevent confusion. Here some points:

- I'd favor a `.com` TLD.
- I would try to register a domain without a hyphen in it.
