### ISSUE TITLE
Unsupported tokens (deny list)

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#407]
The settlements can fail for some "unsupported tokens" 

One example https://gnosisinc.slack.com/archives/CPZA1AGKY/p1618213983034600

We should disallow trading for tokens that are known to be unsupported. 
I think the backend is considering to use a black list, we might want to inform users about this:

cc/ @fleupold

**Comment by fleupold** [comment]
My weak personal preference would be to label those tokens as "not found" (similar to when there is no liquidity between the token and ETH) and not specifically mention the fact that they are not supported due to some deny list (as questions on how this is decentralized may arise).

**Comment by anxolin** [comment]
That would be fine with me. Any list we can use for this? maybe is good to have it in the NPM package?

**Comment by vkgnosis** [comment]
For reference this is the kick token https://etherscan.io/address/0xC12D1c73eE7DC3615BA4e37E4ABFdbDDFA38907E which is denylisted on the mainnet orderbook backend.

**Comment by anxolin** [comment]
As discussed today, we will try to have a more specific error message.

@fleupold mentioned that the backend could already return an error code associated with the token not being supported by the protocol. 

The FE would handle this error:
- Don't ask again for the same token, at least in 10min (it's possible one unsuported token becomes supported in the future)
- Show an explanatory message, add a link to the FAQ
- Write a FAQ entry explaining the problem

Felix, maybe you would like to make a suggestion for the FAQ?

cc/ @avsavsavs @annamsgeorge

**Comment by fleupold** [comment]
@nlordell did a pretty good explanation in https://gnosisinc.slack.com/archives/CPZA1AGKY/p1619796060212800

Maybe something like:

> Unfortunately, CowSwap does not support some tokens, in particular those that apply transfer fees. While these tokens implement the typical ERC20 interface, when calling the `transfer` and `transferFrom` methods, the actual amount the receiver will get will be smaller than the specified sent amount. This cause problems with CowSwap's settlement logic which expects the received amount (e.g. from a Uniswap interaction) to be fully transferable to the trader.

**Comment by anxolin** [comment]
Sounds perfect @fleupold , only minor comment/question about this part:

> in particular those that apply transfer fees. While these tokens

I thought there was an issue also with the ones that modify the supply too, like AMPL. If that's the case, should that part be more general?

**Comment by fleupold** [comment]
Those tokens are only an issue if they rebased downwards and therefore the Uniswap reserves are out of sync with the real values. We don't unsupport them categorically (only when they are undercollateralized). Also explaining this to the user might not be simple. Normally those tokens try to contain at least some good pool on Uniswap so they should work.

**Comment by fleupold** [comment]
FYI, the backend is now returning a designated error for Unsupported tokens so that they can be displayed more explicitly to the user
