### ISSUE TITLE
Add Menu

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#418]
**Description**
Add a app menu with the main pages and links.

Similar to Uniswap menu:
![image](https://user-images.githubusercontent.com/2352112/114590397-01d32700-9c89-11eb-8146-fde8c38e4b96.png)

The task is to add back the menu of the app. 

The menu could look like:
- About ✳️
- Code
- FAQ ✳️
- Discord

✳️: the ones that are new. The others were already added some time ago.

cc/ @annamsgeorge

**Comment by annamsgeorge** [comment]
Links:

FAQ: to be added in mark down, content still pending
Code: https://github.com/gnosis/gp-v2-contracts
Discord: https://discord.gg/egGzDDctuC

**Comment by anxolin** [comment]
@annamsgeorge are you sure the code should point to the contracts instead of https://github.com/gnosis/gp-swap-ui? 

Note that uniswap also points to their UI, not the contracts. In the UI readme you can easily find the link to the contracts.

**Comment by W3stside** [comment]
closed by #427

**Comment by W3stside** [comment]
unless @annamsgeorge we need to change the url? can be new pr

**Comment by anxolin** [comment]
Yes, let's merge and see what anna says about the "Code" link. If we need to change, we can do separatelly
