### ISSUE TITLE
Move "Feedback" button 

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-swap-ui#437]
The "Feedback" button gets in the way of some functionality both on desktop and mobile.

Consider movnig it up/down on mobile/desktop, respectively. Another option could be to go the `z-index` route.

Mobile:
![Screenshot from 2021-04-15 11-35-23](https://user-images.githubusercontent.com/21335563/114856172-b337a100-9dde-11eb-8bc8-c613bc7f9d20.png)

**Comment by anxolin** [comment]
I've done this PR #295 where we do the button ourselves, so we can style it. I used some absolute positioning, and @michelbio wants to style nicely
