### ISSUE TITLE
.env domain prefixes need to be changed for launch

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-swap-ui#446]
Although this is correct right now, it'll change before the release.
Just to keep in mind.
Create an issue maybe? :shrug:

_Originally posted by @alfetopito in https://github.com/gnosis/gp-swap-ui/pull/441#discussion_r614223828_

**Comment by anxolin** [comment]
Solved by https://github.com/gnosis/gp-swap-ui/pull/441
