### ISSUE TITLE
Mobile- Uniswap Artefact

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#479]
**Describe the bug**
Thee address bar has Uniswap coloring on mobile devices

![1618996662202](https://user-images.githubusercontent.com/34510341/115530632-3d2ab280-a294-11eb-81b7-d5a5933fb056.png)

**Comment by anxolin** [comment]
What?? :) 

How did you do this. In IOS doesn't have that color. 
This is just in a regular browser? How do I reproduce?

@michelbio @W3stside I would be suspicious of our manifest.json, but it looks like the color is ok there.

**Comment by MareenG** [comment]
I used Chrome with an Android Phone(Xiaomi Redmi Note 8 Pro).  It is still bright pink on my phone

**Comment by MareenG** [comment]
But no colouring in the MM browser

**Comment by anxolin** [comment]
Can any of you @biocom  / @W3stside can take a look to this. I don't have any android phone available. My guess was the Manifest, but it must be sth else.

**Comment by anxolin** [comment]
Ahhh, I think I found it!!!!! I will do a PR, I cannot test, but let me know if it works :)

**Comment by biocom** [comment]
@anxolin 
> <meta name="theme-color" content="#ff007a" />
in
`public/index.html`

**Comment by anxolin** [comment]
yep, I saw it and here is a PR.
https://github.com/gnosis/gp-swap-ui/pull/510

@MareenG @biocom the test link is available, can u review the PR?
