### ISSUE TITLE
Wrong link in About section 

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#485]
**Describe the bug**
<img width="570" alt="Bildschirmfoto 2021-04-22 um 10 31 59" src="https://user-images.githubusercontent.com/34510341/115682800-19c83c00-a356-11eb-9ff7-7a8722bb7633.png">
Links to the Landing page. I guess this should link to an article or similar

**Comment by MareenG** [comment]
I guess it should link to https://explore.flashbots.net/

**Comment by alfetopito** [comment]
You are correct, that's where it should point to https://github.com/gnosis/gp-swap-ui/pull/459#discussion_r616853540

**Comment by alfetopito** [comment]
Addressed on https://github.com/gnosis/gp-swap-ui/pull/496
