### ISSUE TITLE
About - Typos, comments, enhancment ideas

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#486]
1. Add a link to further reading material about COWs
<img width="526" alt="Bildschirmfoto 2021-04-22 um 10 34 45" src="https://user-images.githubusercontent.com/34510341/115683164-762b5b80-a356-11eb-8726-70708515c39d.png">
Might be good to add additional reading resources here if a user wants to know more about it
Maybe the same as in FAQ - https://en.wikipedia.org/wiki/Coincidence_of_wants
They can google it but might be more convenient to directly click on a link

**Comment by MareenG** [comment]
Same as in FAQ - https://en.wikipedia.org/wiki/Coincidence_of_wants

**Comment by MareenG** [comment]
2. This should be probably sth the user knows but still could be good to write automated market maker once
<img width="565" alt="Bildschirmfoto 2021-04-22 um 12 09 25" src="https://user-images.githubusercontent.com/34510341/115697617-fd330080-a363-11eb-9900-baa4f4270e67.png">

3.  Add a happy cow  icon instead of the :) 
<img width="553" alt="Bildschirmfoto 2021-04-22 um 12 09 55" src="https://user-images.githubusercontent.com/34510341/115697830-39666100-a364-11eb-8dc6-0f4f75a336fa.png">

**Comment by alfetopito** [comment]
Adding another one that I noticed and Vinas confirmed it should be `Maximal` on both
![screenshot_2021-04-22_09-24-51](https://user-images.githubusercontent.com/43217/115751736-5132ea80-a34e-11eb-9eaa-3cb3b2c1b94b.png)

**Comment by anxolin** [comment]
About 1. I think @annamsgeorge don't want to add links, so the user don't jump around from this page to other pages. 

All the rest points, I agree.

Also, I would add at the end a link to the FAQ, so the user can continue learning more. Chances are that a user that makes it to the end of the about, will be hungry of more information, and the FAQ looks like the next place to go.

**Comment by MareenG** [comment]
Change **COW** to **CoW* as confirmed in #488 

<img width="536" alt="Bildschirmfoto 2021-04-23 um 10 23 00" src="https://user-images.githubusercontent.com/34510341/115842256-ecdf5c00-a41d-11eb-87a6-bb7f1ed2831a.png">*
<img width="545" alt="Bildschirmfoto 2021-04-23 um 10 22 44" src="https://user-images.githubusercontent.com/34510341/115842345-04b6e000-a41e-11eb-8681-484a98b3c6e1.png">

**Comment by annamsgeorge** [comment]
In that case we should also change the title and use a small letter case "o":

Coincidence of Wants (CoW)
