### ISSUE TITLE
FAQ - Typos, comments and enhancements

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#488]
I will list here typos, inconsistencies etc for the FAQ section

1. CoW vs COW - in the About section all letters are capitalized in the FAQ not should be consistent

**Comment by MareenG** [comment]
2. The abbreviation of COW is introduced in several places 
<img width="583" alt="Bildschirmfoto 2021-04-22 um 10 51 16" src="https://user-images.githubusercontent.com/34510341/115685900-f488fd00-a358-11eb-8231-c28cf45ecf9c.png">

I would either remove the abbreviation  in the later cases or only state the abbreviation

**Comment by MareenG** [comment]
3. remove space
<img width="583" alt="Bildschirmfoto 2021-04-22 um 10 54 34" src="https://user-images.githubusercontent.com/34510341/115686738-cfe15500-a359-11eb-8928-375080b9ee8d.png">
4. Not sure about this one but shouldn't it be orders? 
<img width="575" alt="Bildschirmfoto 2021-04-22 um 10 56 45" src="https://user-images.githubusercontent.com/34510341/115686768-d8399000-a359-11eb-8c96-1a7574d4dba9.png">
5. proof
<img width="573" alt="Bildschirmfoto 2021-04-22 um 10 57 08" src="https://user-images.githubusercontent.com/34510341/115686901-f4d5c800-a359-11eb-9bb3-7ba72ab1abf5.png">
6. Suggestion: make it more prominent maybe bold or coloured
<img width="578" alt="Bildschirmfoto 2021-04-22 um 10 57 22" src="https://user-images.githubusercontent.com/34510341/115687031-10d96980-a35a-11eb-9f9f-54a50062eac8.png">

**Comment by MareenG** [comment]
7. As this is a selling point of COW I would highlight this a bit more
<img width="572" alt="Bildschirmfoto 2021-04-22 um 11 03 08" src="https://user-images.githubusercontent.com/34510341/115687482-80e7ef80-a35a-11eb-9e5f-28abaa905326.png">

**Comment by MareenG** [comment]
8. It is the only footnote one * might be enough

<img width="575" alt="Bildschirmfoto 2021-04-22 um 11 06 17" src="https://user-images.githubusercontent.com/34510341/115688247-46328700-a35b-11eb-8b74-9981bdf90642.png">

9. Spacing is a bit narrow
<img width="562" alt="Bildschirmfoto 2021-04-22 um 11 07 06" src="https://user-images.githubusercontent.com/34510341/115688319-58acc080-a35b-11eb-8085-5dbc7d6fb96b.png">

10. Offer exit solution as described in #487 
<img width="694" alt="Bildschirmfoto 2021-04-22 um 11 08 12" src="https://user-images.githubusercontent.com/34510341/115688400-69f5cd00-a35b-11eb-9acb-3053d92c8dfd.png">

**Comment by MareenG** [comment]
11. Maybe add the image from the About section here aswell
<img width="586" alt="Bildschirmfoto 2021-04-22 um 11 52 24" src="https://user-images.githubusercontent.com/34510341/115694735-6f561600-a361-11eb-8d7c-9f36ee2cc327.png">

12. add the link to Coincidence of Wants instead of explained
<img width="584" alt="Bildschirmfoto 2021-04-22 um 11 51 42" src="https://user-images.githubusercontent.com/34510341/115694881-9280c580-a361-11eb-84ba-6e7fb93becaf.png">

13. Maximal/ Miner Extractable Value (MEV)- write down the full name onces
<img width="593" alt="Bildschirmfoto 2021-04-22 um 11 51 27" src="https://user-images.githubusercontent.com/34510341/115695031-ba702900-a361-11eb-97c6-f7a72e66532e.png">

**Comment by alfetopito** [comment]
@annamsgeorge @avsavsavs could you review the points Mareen raised?
We are happy to fix it afterwards

**Comment by avsavsavs** [comment]
1. Should be CoW - uniform across all places
2. Since its a new term, from comms side we prefer to leave the abbreviation so users can always pick up the CoWs reference
3. yes, incorrect space there.
4. yes, should be "orders best settlement"
5. yes, should be "proof"
6. 100%, make "at your own risk" bold
7.  100% maybe we can just put in in bold
8. I think that is a markdown error, I think its trying to bold the wording but not so sure what words are to be highlighted
9. I think that is a markdown error, it seems to not have picked up the spacing
10. Yes, close button would be helpful as long as its not much work to add
11. I would say no, since no questions have image support. Also this way we differentiate from the about section and the FAQ
12. Yes,
13. Yes, and also delete the Initially please.

What do you think @annamsgeorg?

**Comment by anxolin** [comment]
your tag to @annamsgeorge didn't work.

Great! thanks for the thorough review @MareenG

**Comment by MareenG** [comment]
I had two more points yesterday which I forgot to add... 
14. Link to GPv2 material
<img width="554" alt="Bildschirmfoto 2021-04-23 um 09 57 15" src="https://user-images.githubusercontent.com/34510341/115838806-56f60200-a41a-11eb-8cf0-492031b7ad9b.png">
15. Link Milk it to landing page
<img width="565" alt="Bildschirmfoto 2021-04-23 um 09 57 23" src="https://user-images.githubusercontent.com/34510341/115838863-6412f100-a41a-11eb-9825-6c7ec67819a1.png">

**Comment by avsavsavs** [comment]
No problem :) 

14. Would be good to link but the problem is that the dev docs will not be ready for launch so better just leave it like that. 
15. Very good idea

**Comment by annamsgeorge** [comment]
Jupp agree with all final responses from Alex V. Thanks Mareen for looking throroughly through it!!
