### ISSUE TITLE
Wrong discord Link FAQs

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#489]
**Describe the bug**
<img width="537" alt="Bildschirmfoto 2021-04-22 um 11 08 39" src="https://user-images.githubusercontent.com/34510341/115688535-8b56b900-a35b-11eb-826a-a993530e2fa2.png">
 Currently links to **Uniswap** - Discord

**Comment by alfetopito** [comment]
Fixed by https://github.com/gnosis/gp-swap-ui/pull/495
