### ISSUE TITLE
Back to the future :) 

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#490]
Wrong date in disclaimer
<img width="276" alt="Bildschirmfoto 2021-04-22 um 11 16 59" src="https://user-images.githubusercontent.com/34510341/115689409-57c85e80-a35c-11eb-9918-4d62d7f21e02.png">

**Comment by alfetopito** [comment]
Addressed on https://github.com/gnosis/gp-swap-ui/issues/490
