### ISSUE TITLE
Duplicate home button

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#491]
**Is your feature request related to a problem? Please describe.**
Both, the logo and Swap, lead to the landing page. IMO this is a duplicate. The logo might be sufficient
<img width="417" alt="Bildschirmfoto 2021-04-22 um 12 05 57" src="https://user-images.githubusercontent.com/34510341/115696664-30c15b00-a363-11eb-816c-d08db120d994.png">

**Comment by anxolin** [comment]
We can happily delete. It's more explicit. Uniswap has that too. 

@annamsgeorge @biocom do we delete or leave it like this?

**Comment by biocom** [comment]
@MareenG It's common to have the logo link to the homepage. In our case we also have the SWAP | ABOUT menu items, which is just there to be more explicit as @anxolin pointed out.
