### ISSUE TITLE
Footer links - Position changed? 

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#492]
**Describe the bug**
Whre the links in the footer moved by purpose to the center? 

old
<img width="1348" alt="Bildschirmfoto 2021-04-22 um 12 20 17" src="https://user-images.githubusercontent.com/34510341/115698951-767f2300-a365-11eb-9ca4-8ec5b21baef9.png">

new
<img width="1292" alt="Bildschirmfoto 2021-04-22 um 12 20 28" src="https://user-images.githubusercontent.com/34510341/115698954-77b05000-a365-11eb-8a1d-192f8018a717.png">

**Comment by anxolin** [comment]
Closed by #502
