### ISSUE TITLE
Warn user if he wraps to much ETH

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#499]
**Description**
Warn the user if after wrapping they are leaving their account with too little balance.
![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/d8601746-915a-4509-ba35-f5488e87dabd)

If we don't do this, the user might end up with all his ETH wrapped, and no more ETH to approve WETH (or other tokens).

**Describe the solution you'd like**
![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/07539a0e-0d0a-45d9-aef4-3cea97cc2bf3)

Show a warning if the current balance minus the amount about to wrap are less than 0.1 ETH (just a random suggestion)

When the warning is visible, the button is also showing a confirmation dialog. This way we make the user more aware of what they are doing. He can ignore the warnings and continue, even if that means that he wraps all his ETH (some wallets don't need ether to operate, so maybe that's what he really wants)

Additionally, the MAX button should leave at least enough ETH for approving the WETH later. 

**Describe alternatives you've considered**
instead of 0.1 ETH we could estimate how much it cost to do 1 WRAP and 2-3 approvals at current gas prices. However I suggested a static value for simplicity.

**Additional context**

cc: @annamsgeorge

**Comment by annamsgeorge** [comment]
really good point!!
