### ISSUE TITLE
Design issues etc Meta Mask browser

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#503]
List of minnor bugs or issues with the MM browser

1. If I click on the FAQs in the Menu, the Menu stays on the screen until one clicks somewhere else on the screen. It is the same in a web browser but on Mobile this is a bit annoying as it covers the text.
_It is the same for other mobile browser_
![1619166838653](https://user-images.githubusercontent.com/34510341/115844622-4c3e6b80-a420-11eb-885e-2ae758850836.jpg)
2. Link not working in MM browser 
![1619166838631](https://user-images.githubusercontent.com/34510341/115865372-7f8cf480-a438-11eb-9ebd-c63aaace9a01.jpg)

_But works e.g. in Chrome on mobile_

**Comment by MareenG** [comment]
3. Feedback icon is blocking some of the info which is a bit annoying. One can scroll and all the info is visibile but maybe we could consider another position to im prove UX. 



![1619596069572](https://user-images.githubusercontent.com/34510341/116366923-15dd6380-a807-11eb-9ccd-1e8a75ade56f.jpg)
4. Disalignment of the confirm box
![1619596083681](https://user-images.githubusercontent.com/34510341/116366954-1ece3500-a807-11eb-9d10-7e017d7300d6.jpg)

**Comment by biocom** [comment]
Point 1 being addressed in #588

**Comment by biocom** [comment]
@MareenG On point 3 we had some discussion around this:
- Even though you can scroll up/down, I think we acknowledge that it might stand in the way. 
- At the same time we think that at this stage, we wouldn't receive the amount of feedback we got, were it not for having the button in a more prominent/visible spot like now. 

The alternative would be to put it somewhere in the footer or main menu (at least just for mobile). But we'd envision getting less feedback at this stage as a result.

**Comment by biocom** [comment]
For point 4. I created issue https://github.com/gnosis/gp-swap-ui/issues/592

**Comment by biocom** [comment]
@MareenG As for point 2, can you tell me how to reproduce? I tried to reproduce it myself but it seemed to work fine. Details:

- Android
- MetaMask Dapp browser
- URL's tested: [cowswap.exchange](url) & [cowswap.eth](url)

All allowed me to connect my wallet and use the interface.

**Comment by MareenG** [comment]
@biocom concerning point 2, I forgot to add which link didn't work. It was a link in the FAQ but this is already solved.

**Comment by biocom** [comment]
Closing this ticket as some are already addressed or separate tickets were opened for them. @MareenG feel free to reopen in case you feel this should stay open otherwise.
