### ISSUE TITLE
Improve styles in ToC for FAQ

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#515]
**Description**
Improve styles in the table of content (ToC) for FAQ

![image](https://user-images.githubusercontent.com/2352112/115893378-65630e80-a458-11eb-9187-96947e6500a3.png)

@biocom  magic. @annamsgeorge has some ideas, maybe she can comment in this issue

**Comment by annamsgeorge** [comment]
Cool!

Two thoughts:

<img width="172" alt="Screenshot 2021-04-23 at 11 25 14" src="https://user-images.githubusercontent.com/33424780/115893782-defafc80-a458-11eb-805f-ab08c4f70721.png">



And it would look better if not everything was links, but instead at the end of each question is an arrow that can  be clicked to reach the question:

<img width="109" alt="Screenshot 2021-04-23 at 11 25 45" src="https://user-images.githubusercontent.com/33424780/115893856-f1753600-a458-11eb-8b7c-dd4791c4ae3e.png">

**Comment by anxolin** [comment]
Closed by #567
