### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#536]
**Describe the bug**
<img width="324" alt="Bildschirmfoto 2021-04-27 um 13 10 06" src="https://user-images.githubusercontent.com/34510341/116232099-f76d5e80-a759-11eb-9688-0007649dec0d.png">
This currently links to https://github.com/gnosis/gp-v2-contracts
Shouldn't it rather link to https://github.com/gnosis/gp-swap-ui

**Comment by anxolin** [comment]
@MareenG fixed here https://github.com/gnosis/gp-swap-ui/pull/541, let us know if all good :)

**Comment by MareenG** [comment]
Yes, looks all good :)
