### ISSUE TITLE
Price discrepancy between Uniswap and Cowswap

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#537]
**Describe the bug**
For some token pairs the price on CowSwap is different than on Uniswap

**How to Reproduce**
1. Go to Cowswap and Uniswap
2. Chose a token pair to trade against
3. Insert same from amounts on Uni and Cowswap
4. Compare

**Expected behavior**
The prices should be the same. 

**Screenshots**
Rinkeby
<img width="1615" alt="Bildschirmfoto 2021-04-27 um 12 55 18" src="https://user-images.githubusercontent.com/34510341/116244084-e0356d80-a767-11eb-941a-d5720a40293b.png">
Mainnet
<img width="1519" alt="Bildschirmfoto 2021-04-27 um 13 02 27" src="https://user-images.githubusercontent.com/34510341/116243969-c3009f00-a767-11eb-9837-c47aa6741b9c.png">

Other token pairs
Rinkeby
<img width="1473" alt="Bildschirmfoto 2021-04-27 um 14 29 50" src="https://user-images.githubusercontent.com/34510341/116244062-d9a6f600-a767-11eb-886e-cc408fe4b108.png">
Mainnet
<img width="1912" alt="Bildschirmfoto 2021-04-27 um 14 33 21" src="https://user-images.githubusercontent.com/34510341/116244068-dad82300-a767-11eb-9669-3e3632dd836e.png">

**Comment by anxolin** [comment]
This issue will become less relevant now. In next version we break up with Uniswap price and we start using our own. 
Last day I check, I was getting consistent prices.

I would only look into this if we think this is covering up some issue. 
Otherwise, I would close.

I think with the new changes we are planning, this issue could be killed. What do you think @alfetopito @W3stside @annamsgeorge

**Comment by alfetopito** [comment]
Agree the prices will differ and make no sense to compare they are identical.

BUT! In theory the prices should be at least equal or better, since we'll be tapping into different liquidity sources, right?

**Comment by anxolin** [comment]
> BUT! In theory the prices should be at least equal or better, since we'll be tapping into different liquidity sources, right?

Once we use the new price API yes, thats my hope on getting consistently better prices

**Comment by anxolin** [comment]
Closing, I think is not relevant any more. Please reopen if anyone things we have any issue
