### ISSUE TITLE
The fee field is shown two times

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#547]
**Describe the bug**
The fee field is shown two times

**How to Reproduce**
See conversation and video:
https://gnosisinc.slack.com/archives/CSGLUC1BN/p1619533192019200

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/116279668-197dd580-a788-11eb-9c9d-5f57bf19c96c.png)

**Comment by MareenG** [comment]
Experienced this also for another token pair than UNI/DAI
<img width="473" alt="Bildschirmfoto 2021-04-29 um 12 15 57" src="https://user-images.githubusercontent.com/34510341/116536183-e7ce5100-a8e4-11eb-8bd5-abd8d3ed8cc7.png">

The first fee is shown in the **to** and the second one in the **from** token
