### ISSUE TITLE
CowSwap shows a blank page

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-swap-ui#557]
**Describe the bug**
Reported by a user on Discord:

```
cowswap shows a blank page when I did the following:
-Selected a token BAL
-Put 1 BAL
-Change wETH to ETH.

The javascript console shows an error: Invariant Failed.
```

**How to Reproduce**

See above

**Expected behavior**
The app should not crash

**Screenshots**

**Additional context**
Also, if it's relevant for the described bg, add information like the browser or OS.

**Comment by zerpajose** [comment]
https://user-images.githubusercontent.com/5432286/116482922-1b14cf80-a854-11eb-86e4-aaf9fadc49e9.mp4

**Comment by anxolin** [comment]
Good catch!

It happens no matter the token you select, what is broken is: **making a buy order where ETH is the sell token**

- 1. Select ETH/XXX, being XXXX any token
- 2. Input any amount in the TO

We'll address this right away 💪

Anyways, ETH/XXX trade cannot happen directly, ETH need to be wrapped first to WETH.
Once wrapped, you should be able to do buy orders WETH/XXX and sell orders WETH/XXX

cc/ @MareenG

**Comment by W3stside** [comment]
this doesn't happen to me in 0.10.1...
