### ISSUE TITLE
Considering a mute button

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#561]
**Is your feature request related to a problem? Please describe.**
We got some user feedback that the moo could be annoying for many consecutive trades. 

**Describe the solution you'd like**
If possible we could offer a mute button for CowSwap

**Additional context**
<img width="493" alt="Bildschirmfoto 2021-04-29 um 11 38 23" src="https://user-images.githubusercontent.com/34510341/116531420-7049f300-a8df-11eb-9448-31c840292375.png">

**Comment by alfetopito** [comment]
I think we could add a toggle in the settings to disable the sounds

**Comment by anxolin** [comment]
Great! Yep, we also discussed that this would be probably for launch and we would see the feedback. 
For now, it hasn't been that strong feedback (compare with what we thought we could get)

Anyways, I also created this other #565 so closing in favour of it.
