### ISSUE TITLE
Links in Menu not well highlighted

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#627]
**Describe the bug**
When scrolling over the Links in the Menu the underline is only shown for the link one previously clicked on.

**How to Reproduce**
1. Go to 'CowSwap'
2. Click on '...'
3. Scroll down over the Links

**Expected behavior**
I would assume that the link one hovers over is highlighted (bold or underlined) not the one one prior clicked on.

**Screenshots**

https://user-images.githubusercontent.com/34510341/118240077-da939380-b49a-11eb-899d-0fdc9de0512d.mov

**Comment by biocom** [comment]
Fixed in https://pr622--gpswapui.review.gnosisdev.com/ #622
