### ISSUE TITLE
Wrong notification for Fees exceeding from amount

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#637]
**Describe the bug**
Insufficient liquidity for this trade is displayed when actually the fees exceed the amount

**How to Reproduce**
1. Enter an amount close to the fee amount as from token
2. Insufficient liquidity for this trade is displayed

**Expected behavior**
Fees exceed from amount should be displayed instead

**Screenshots**
<img width="1562" alt="Bildschirmfoto 2021-05-18 um 10 20 06" src="https://user-images.githubusercontent.com/34510341/118618647-20669980-b7c4-11eb-9416-405859d5c156.png">
<img width="1474" alt="Bildschirmfoto 2021-05-18 um 10 20 28" src="https://user-images.githubusercontent.com/34510341/118618652-2197c680-b7c4-11eb-948b-4af26b421d27.png">

**Comment by W3stside** [comment]
good find, will investigate.
