### ISSUE TITLE
Pillar wallet issue

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#699]
**Describe the bug**
Pillar is an SC that only deploy the contract after transacting for the first time

I spent ETH in wrapping it, and approving WETH, and only after i was informed it was not compatible.

Can we prevent this just by having in the list of unsupported wallets. I connected using WalletConnect, so theoretically we should have the name.

**Comment by alfetopito** [comment]
As mentioned on Slack, would be nice, but we can't.
AFAICT, there's nothing provided by Pillar wallet thought WC that can help us identify it is a Pillar wallet.

I'm surprised you were able to Wrap ETH though, as that requires you to "activate" the wallet.
And doing so will deploy the wallet, transforming it from a regular EOA to a Smart Contract.

**Comment by anxolin** [comment]
It let you know in advance. I'll make a PR for it to prevent the issue. 
![image](https://user-images.githubusercontent.com/2352112/119974364-d6946500-bfb4-11eb-845f-33c0904fea60.png)

Also, interesting that I manage to trick the app* into signing, and I manage to sign with PILLAR. The backend refused the hash thought for balance. I'm not 100% sure what happened, but probably it was signed with the EIP-1271 which is not yet supported, and the hash yields a weird address for the backend cause they use EIP-712. 

![IMG_6ACFE6765D27-1](https://user-images.githubusercontent.com/2352112/119975489-363f4000-bfb6-11eb-90cd-f7353e0e7c55.jpeg)

(* `manage to trick the app`), I mean I hacked the code to hardcode that is NOT a smart contract wallet
